{% set name = "mbedtls" %}
{% set version = "2.24.0" %}
{% set sha256 = "d436ae4892bd80329ca18a3960052fbb42d3f1f46c7519711d6763621ca6cfa0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/ARMmbed/mbedtls/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - perl
    - python 3.6
  run:

test:
  commands:
    - test -f ${PREFIX}/lib/libmbedcrypto.so
    - test -f ${PREFIX}/lib/libmbedx509.so
    - test -f ${PREFIX}/lib/libmbedtls.so
    - test -f ${PREFIX}/include/mbedtls/certs.h
    - mbedtls_selftest

about:
  home: "https://tls.mbed.org/"
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "An open source, portable, easy to use, readable and flexible SSL library"
  doc_url: "https://tls.mbed.org/kb"
  dev_url: "https://github.com/ARMmbed/mbedtls"
