{% set name = "exifreader" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ExifReader-{{ version }}.tar.gz
  sha256: 1b496a2f815ace94944a3211042f00019a666826e1f432da89583f2daab41a65

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  run_exports:
    -  {{ pin_subpackage(name|lower, max_pin="None") }}

requirements:
  host:
    - python >=3.4,<4
    - pip
    - setuptools
  run:
    - python >=3.4,<4
    - defusedxml >=0.6.0

test:
  imports:
    - exifreader
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/Cyb3r-Jak3/exifreader
  summary: Read Exif metadata from tiff and jpeg files.
  license: BSD-3-Clause
  license_file: LICENSE.txt
