{% set name = "cudatoolkit" %}
{% set version = "11.4.4" %}
{% set sha256 = "44545a7abb4b66dfc201dcad787b5e8352e5b7ddf3e3cc5b2e9177af419c25c8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://developer.download.nvidia.com/compute/cuda/11.4.4/local_installers/cuda_11.4.4_470.82.01_linux.run
    sha256: {{ sha256 }}

build:
  number: 0
  skip: True # [osx]
  detect_binary_files_with_prefix: False
  binary_relocation: False

test:
  commands:
    - nvcc --version

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license: PROPRIETARY
  summary: 'NVIDIA CUDA Toolkit'

extra:
  skip-lints:
    - in_other_channels
    - should_be_noarch_generic
    - build_number_needs_bump

