{% set name = "ChromBPNet" %}
{% set version = "1.0.1" %}
{% set sha256 = "640bbf75e34fb2428ddbdb4de6ac646d2353ebe8885f4b02f86c9918294f1059" %}
# Define build matrix for GPU vs. CPU
{% set chrombpnet_variant = chrombpnet_variant or "cuda" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0]|lower }}/{{ name|lower }}/chrombpnet-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [py2k or py>=40]
  string: {{ chrombpnet_variant }}_py{{ py }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  entry_points:
    - chrombpnet = chrombpnet.CHROMBPNET:main
    - print_meme_motif_file = chrombpnet.data.__init__:print_meme_motif_file
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  run_exports:
    -  {{ pin_subpackage(name|lower, max_pin="x") }}

requirements:
  host:
    - pip
    - python
    - h5py >=2.10.0
    - matplotlib-base >=3.3.1
    - matplotlib-venn >=0.11.6
    - numpy >=1.23.4
    - pandas >=1.3.4
    - pyfaidx >=0.6.1
    - scikit-learn >=1.1.2
    - scipy >=1.4.1
    - cuda-version  {{ cuda_compiler_version }} # [chrombpnet_variant == "cuda"]
    - tensorflow >=2.8.0 cuda11*  # [chrombpnet_variant == "cuda"]
    - tensorflow >=2.8.0 cpu_*  # [chrombpnet_variant == "cpu"]
    - tensorflow-estimator >=2.8.0 cuda11*  # [chrombpnet_variant == "cuda"]
    - tensorflow-estimator >=2.8.0 cpu_*  # [chrombpnet_variant == "cpu"]
    - tensorflow-probability >=0.15.0
    - protobuf >=3.20
    - tqdm >=4.48.2
    - deepdish >=0.3.7
    - deeplift >=0.6.13.0
    - modisco >=0.5.16.0
    - modisco-lite >=2.0.7
    - weasyprint >=52.5
    - shap
    - samtools
    - bedtools
    - ucsc-bedgraphtobigwig
    - pybigwig
    - meme
    - google-cloud-sdk
  run:
    - python
    - h5py >=2.10.0
    - matplotlib-base >=3.3.1
    - matplotlib-venn >=0.11.6
    - numpy >=1.23.4
    - pandas >=1.3.4
    - pyfaidx >=0.6.1
    - scikit-learn >=1.1.2
    - scipy >=1.4.1
    - cuda-version {{ cuda_compiler_version }} # [chrombpnet_variant == "cuda"]
    - tensorflow >=2.8.0 cuda11*  # [chrombpnet_variant == "cuda"]
    - tensorflow >=2.8.0 cpu_*  # [chrombpnet_variant == "cpu"]
    - tensorflow-estimator >=2.8.0 cuda11*  # [chrombpnet_variant == "cuda"]
    - tensorflow-estimator >=2.8.0 cpu_*  # [chrombpnet_variant == "cpu"]
    - tensorflow-probability >=0.15.0
    - protobuf >=3.20
    - tqdm >=4.48.2
    - deepdish >=0.3.7
    - deeplift >=0.6.13.0
    - modisco >=0.5.16.0
    - modisco-lite >=2.0.7
    - weasyprint >=52.5
    - shap
    - samtools
    - bedtools
    - ucsc-bedgraphtobigwig
    - pybigwig
    - meme
    - google-cloud-sdk

test:
  imports:
    - chrombpnet
  commands:
    - chrombpnet --help
    - print_meme_motif_file --help

about:
  home: https://github.com/kundajelab/chrombpnet
  summary: "Bias factorized, base-resolution deep learning models of chromatin accessibility (chromBPNet)."
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/kundajelab/chrombpnet
  doc_url: https://github.com/kundajelab/chrombpnet/wiki

extra:
  skip-lints:
    - should_be_noarch_python
    - should_not_use_skip_python
    - should_be_noarch_generic
