--- src/Makefile	2018-11-29 14:45:26.000000000 +0000
+++ src/Makefile.new	2019-05-01 23:11:24.743865415 +0000
@@ -29,7 +29,6 @@
 endif
 
 ### Installation dir definitions
-PREFIX = /usr/local
 BINDIR = $(PREFIX)/bin
 
 ### Built-in benchmark for pgo-builds
