{% set name = "T-COFFEE" %}
{% set version = "13.45.0.4846264" %}
{% set sha256 = "c8e5ba17de11ddf07cf2ed37f077d81c1432d55b77761f115f9374de6f8d0d03" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 6
  skip: True  # [osx]

source:
  # The latest stable release is at http://www.tcoffee.org/Packages/Stable/Latest/ ,
  # but is then archived at http://www.tcoffee.org/Packages/Archives/
  url: https://s3.eu-central-1.amazonaws.com/tcoffee-packages/Stable/Latest/T-COFFEE_distribution_Version_{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - perl-xml-simple
    - blast
    - clustalo
    - clustalw
    - consan # [not osx]
    - dca
    - dialign-tx 1.0.2
    - famsa
    - kalign2
    - mafft 7.310
    - muscle
    - mustang 3.2.3
    - pasta
    - perl
    - phylip
    - poa 2.0 # [not osx]
    - prank
    - probcons
    - probconsrna
    - ruby
    - sap
    - tmalign
    - viennarna 2.1.9
  run:
    - blast
    - clustalo
    - clustalw
    - consan # [not osx]
    - dca
    - dialign-tx 1.0.2
    - famsa
    - kalign2
    - mafft 7.310
    - muscle
    - mustang 3.2.3
    - pasta
    - perl
    - phylip
    - poa 2.0 # [not osx]
    - prank
    - probcons
    - probconsrna
    - ruby
    - sap
    - tmalign
    - viennarna 2.1.9
    
test:
  commands:
    - HOME=/tmp t_coffee --help

about:
  home: https://github.com/cbcrg/tcoffee
  license: GPL-2.0-only
  license_file: license.txt
  summary: "A collection of tools for Multiple Alignments of DNA, RNA, Protein Sequence"

extra:
  identifiers:
    - doi:10.1006/jmbi.2000.4042
  skip-lints:
    - in_other_channels
    - build_number_needs_bump
