{% set name = "visualkeras" %}
{% set version = "0.0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 8cd900884da9f39e8de1e431fa3a42686af435cceab83d013b1c17a5ac9c1b97

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - aggdraw >=1.3.11
    - numpy >=1.18.1
    - pillow >=6.2.0
    - imagemagick
    - pip
    - python >=3
    - keras
    - tensorflow
  run:
    - aggdraw >=1.3.11
    - numpy >=1.18.1
    - pillow >=6.2.0
    - imagemagick
    - python >=3
    - keras
    - tensorflow

test:
  imports:
    - visualkeras

about:
  home: https://github.com/paulgavrikov/visualkeras
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Architecture visualization of Keras models" 
  dev_url: https://github.com/paulgavrikov/visualkeras
