{% set name = "cbor2" %}
{% set version = "5.2.0" %}
{% set sha256 = "a33aa2e5534fd74401ac95686886e655e3b2ce6383b3f958199b6e70a87c94bf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cbor2-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [py<36]
  script:
    - export CBOR2_BUILD_C_EXTENSION=1
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools >=40.7.0
    - setuptools-scm >=1.7.0
  run:
    - python

test:
  imports:
    - cbor2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/cbor2/
  summary: Pure Python CBOR (de)serializer with extensive tag support
  license: MIT
  license_file: LICENSE.txt
