{% set version = '0.6-4' %}

package:
  name: r-rglpk
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Rglpk_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Rglpk/Rglpk_{{ version }}.tar.gz
  sha256: a28dbc3130b9618d6ed2ef718d2c55df8ed8c44a47161097c53fe15fa3bfbfa6

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf
    - automake
    - pkg-config
    - make

  host:
    - r-base
    - r-slam >=0.1_9
    - glpk

  run:
    - r-base
    - r-slam >=0.1_9
    - glpk

test:
  commands:
    - $R -e "library('Rglpk')"

about:
  home: http://R-Forge.R-project.org/projects/rglp/, http://www.gnu.org/software/glpk/

  license: GPL-2 | GPL-3
  summary: R interface to the GNU Linear Programming Kit. 'GLPK' is open source software for
    solving large-scale linear programming (LP), mixed integer linear programming ('MILP')
    and other related problems.

  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
