{% set name = "maxquant" %}
{% set version = "2.0.3.0" %}
{% set sha256 = "463fcd29b41263c33c50c7c7c2cc608bc4b5b3e6806b77a1adc811e0f215af33" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  folder: mq
  fn: mq.zip
  url: https://uofnelincoln.sharepoint.com/:u:/s/UNL-HollandComputingCenter/ERXZ-muR1F9Agme_pthhqaoBejT_5N_e2XlOFqprwBj8Ng?e=h3dLxh&download=1
  sha256: '{{ sha256 }}'

build:
  noarch: generic
  number: 0

  script:
    - cp -r mq/bin $PREFIX
    - cp $RECIPE_DIR/maxquant $RECIPE_DIR/maxquantgui $PREFIX/bin
    - chmod +x $PREFIX/bin/maxquant $PREFIX/bin/maxquantgui
    - chmod +x $PREFIX/bin/MaxQuantCmd.exe
    - chmod +x $PREFIX/bin/MaxQuantGui.exe
    - python $RECIPE_DIR/xmlcombine.py $PREFIX/bin/conf/modifications.xml $RECIPE_DIR/mod_*.xml > $PREFIX/bin/conf/modifications_temp.xml
    - mv $PREFIX/bin/conf/modifications_temp.xml $PREFIX/bin/conf/modifications.xml

requirements:
  build:
    - python >=3.6
  host:
  run:
    - dotnet 2.1

test:
  commands:
    - maxquant --version 2>&1 | grep {{ version }}

about:
  home: https://maxquant.org/
  doc_url: http://www.coxdocs.org/doku.php?id=maxquant:start
  license: OTHER
  license_family: OTHER
  license_file: LICENSE.pdf
  summary: MaxQuant is a quantitative proteomics software package designed for analyzing large mass-spectrometric data sets. License restricted.

extra:
  identifiers:
    - biotools:MaxQuant
    - biotools:maxquant
    - doi:10.1038/s41592-018-0018-y
    - usegalaxy-eu:maxquant
  skip-lints:
    - should_not_use_fn
    - should_be_noarch_python
    - in_other_channels
