variables:
  HCC_BIOCONDA_UTILS_TAG: "gitlabci-master"
  BIOCONDA_UTILS_BUILD_ARGS: "--loglevel=info --keep-old-work"
  BIOCONDA_UTILS_LINT_ARGS: "--loglevel=info"
  MINICONDA_VER: "4.6.14"
  SUBDAGS: "1"
  SUBDAG: "0"
  LANG: "en_US.UTF-8"
  LC_ALL: "en_US.UTF-8"
  DEFAULT_LINUX_VERSION: "cos7"
  CONDA_OVERRIDE_CUDA: "12.4"

stages:
  - build
  - deploy

build-linux:
  stage: build
  image: quay.io/condaforge/linux-anvil-cos7-x86_64:latest
  except:
    - master
  tags:
    - docker
  before_script:
    - sudo yum update -y -q ca-certificates
    - git config --global http.sslCAinfo /etc/ssl/certs/ca-bundle.crt
    # Workaround for https://github.blog/2022-04-12-git-security-vulnerability-announced/
    - git config --global --add safe.directory ${CI_PROJECT_DIR}
    - export ANACONDA_PREFIX=/opt/conda
    - export HOME=/home/conda
    - scripts/gitlabci-setup.sh
  script:
    - scripts/gitlabci-run.sh
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .cache/conda_build_src
      - .cache/conda_pkgs

deploy-linux:
  stage: deploy
  image: quay.io/condaforge/linux-anvil-cos7-x86_64:latest
  only:
    - master
  tags:
    - docker
  before_script:
    - sudo yum update -y -q ca-certificates
    - git config --global http.sslCAinfo /etc/ssl/certs/ca-bundle.crt
    # Workaround for https://github.blog/2022-04-12-git-security-vulnerability-announced/
    - git config --global --add safe.directory ${CI_PROJECT_DIR}
    - export ANACONDA_PREFIX=/opt/conda
    - export HOME=/home/conda
    - scripts/gitlabci-setup.sh
  script:
    - scripts/gitlabci-run.sh
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .cache/conda_build_src
      - .cache/conda_pkgs
    policy: pull

