#!/bin/bash

mkdir build && pushd build
cmake -Wno-dev -DCMAKE_INSTALL_PREFIX=${PREFIX} -DCMAKE_PREFIX_PATH=${PREFIX} -DCMAKE_BUILD_TYPE="Release" \
  -DSPIRIT_UI_CXX_USE_QT=OFF -DSPIRIT_USE_CUDA=OFF -DSPIRIT_USE_FFTW=ON -DSPIRIT_USE_OPENMP=ON \
  -DSPIRIT_ENABLE_PINNING=ON -DSPIRIT_ENABLE_DEFECTS=ON -DSPIRIT_BUILD_FOR_PYTHON=ON \
  -DCMAKE_C_COMPILER=${CC} -DCMAKE_CXX_COMPILER=${CXX} -DCMAKE_LINKER=${LD} \
  -DSPIRIT_USE_THREADS=ON ..

make -j 4
make install
popd && pushd core/python
${PYTHON} -m pip install . --no-deps -vvv
