# Based on https://github.com/conda-forge/jbig2dec-feedstock.git, updated to current version
{% set name = "jbig2dec" %}
{% set version = "0.19" %}
{% set ghostscript_tag = "gs9533" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/{{ ghostscript_tag }}/jbig2dec-{{ version }}.tar.gz
  sha256: 279476695b38f04939aa59d041be56f6bade3422003a406a85e9792c27118a37
build:
  number: 0
  run_exports:
    - {{ pin_subpackage('jbig2dec', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - pkg-config
  host:
    - zlib
    - libpng

test:
  commands:
    - jbig2dec --help

about:
  home: https://jbig2dec.com/
  license: AGPLv3
  license_family: AGPL
  license_file: COPYING
  summary: 'A decoder implementation of the JBIG2 image compression format'
  description: |
    JBIG2 is designed for lossy or lossless encoding of 'bilevel'
    (1-bit monochrome) images at moderately high resolution, and
    in particular, scanned paper documents. In this domain it can
    be very efficient, offering compression ratios on the order of
    100:1

extra:
  skip-lints:
    - in_other_channels
