{% set name = "usearch" %}
{% set version = "6.1.544" %}
{% set sha256 = '66789a945bdfd9c31978abfdebcab2dbb8bb37deb1101ab24bd55fb87b23896a' %}
{% set filename = "usearch6.1.544_i86linux32" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://drive5.com/downloads/{{ filename }}.gz
    sha256: {{ sha256 }}

build:
  skip: True # [osx]
  number: 0
  script:
    - gunzip {{ filename }}.gz
    - mkdir -p ${PREFIX}/bin
    - cp {{ filename }} ${PREFIX}/bin/usearch
    - chmod 755 ${PREFIX}/bin/usearch

test:
  commands:
    - usearch -version

about:
  home: https://www.drive5.com/usearch
  summary: 'USEARCH is a unique sequence analysis tool with thousands of users world-wide.'
  license: PROPRIETARY
  license_family: PROPRIETARY
  license_file: LICENSE.txt

extra:
  skip-lints:
    - should_be_noarch_generic
