{% set name = "xmlf90" %}
{% set version = "1.5.4" %}
{% set sha256 = "a0b1324ff224d5b5ad1127a6ad4f90979f6b127f1a517f98253eea377237bbe4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://launchpad.net/xmlf90/trunk/1.5/+download/xmlf90-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [osx]

requirements:
  build:
    - {{ compiler('fortran') }}
    - make
  host:
  run:

test:
  commands:
    - test -f ${PREFIX}/lib/libxmlf90${SHLIB_EXT}

about:
  home: "https://gitlab.com/siesta-project/libraries/xmlf90"
  dev_url: "https://gitlab.com/siesta-project/libraries/xmlf90"
  summary: "xmlf90 is a suite of libraries to handle XML in Fortran."
  license: Custom
  license_family: OTHER
  license_file: LICENSE
