{% set name = "shared-ndarray" %}
{% set version = "1.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 852c3ab6561a1ecdca2b61f7b4db75f406e276294b5862c256fc011fd4a20c57

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - numpy >=1.11.3
    - pip
    - posix_ipc >=1.0.0
    - python 2.7
  run:
    - numpy >=1.11.3
    - posix_ipc >=1.0.0
    - python 2.7

test:
  imports:
    - shared_ndarray

about:
  home: https://github.com/crowsonkb/shared_ndarray
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A pickleable wrapper for sharing NumPy ndarrays between processes using POSIX shared memory."
  dev_url: https://github.com/crowsonkb/shared_ndarray
