{% set name = "vcfstats" %}
{% set version = "0.6.0" %}
{% set sha256 = "a6afdaaa6af96e5f159f2f31428c5f9b3563bb55252e4f79b2306aa8e95fe98d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/vcfstats-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  entry_points:
    - vcfstats = vcfstats.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin="x.x") }}

requirements:
  host:
    - python 
    - poetry >=0.12
    - poetry-core
    - pip
  run:
    - python 
    - cyvcf2 >=0.30.0,<0.31.0
    - lark-parser >=0.12.0,<0.13.0
    - plotnine-prism >=0.3.0,<0.4.0
    - python-slugify >=8.0.0,<9.0.0
    - datar >=0.13.0,<0.14.0
    - py >=1.10.0,<2.0.0
    - argx >=0.2.0,<0.3.0
    - rich >=13.0.0,<14.0.0

test:
  imports:
    - vcfstats
  commands:
    - vcfstats --help

about:
  home: https://github.com/pwwang/vcfstats
  summary: Powerful statistics for VCF files
  license: MIT
  license_file: LICENSE
