{% set name = "nextcloud-api-wrapper" %}
{% set version = "0.2.3" %}
{% set sha256 = "30ac51f86a7a00506a376034f804cc1fe70385496443fb75de6064d7c1f97a6e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nextcloud-api-wrapper-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
  run:
    - python
    - requests >=2.0.1,<3.0
    - six

test:
  imports:
    - nextcloud
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/nextcloud-api-wrapper/
  summary: Python wrapper for NextCloud api
  dev_url: https://github.com/luffah/nextcloud-API
  license: GPL-3.0
  license_file: LICENSE
