{% set name = "ankh" %}
{% set version = "1.10.0" %}
{% set sha256 = "e26f92d81844a1c5550cda5c5367cb176a4af667cb42a79e17e3ef1a9aefdb97" %}
# Define build matrix for GPU vs. CPU
{% set ankh_variant = ankh_variant or "cuda" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ankh-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  string: {{ ankh_variant }}_py{{ py }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin="x") }}

requirements:
  host:
    - python <3.11
    - poetry-core
    - pip
    - cudatoolkit  # [ankh_variant == "cuda"]
    - pytorch >=2.2,<2.4 *cuda11*  # [ankh_variant == "cuda"]
    - pytorch >=2.2,<2.4 *cpu_*  # [ankh_variant == "cpu"]
    - tensorflow >=2.0,<2.10 *cuda11*  # [ankh_variant == "cuda"]
    - tensorflow >=2.0,<2.10 *cpu_*  # [ankh_variant == "cpu"]
    - numpy >=1.22,<=1.24.3
    - scipy
    - transformers
    - pathlib
    - scikit-learn
  run:
    - python <3.11
    - biopython >=1.80.0,<2.0.0
    - transformers >=4.25.1,<5.0.0
    - sentencepiece >=0.1.97,<0.2.0
    - datasets >=2.7.1,<3.0.0
    - cudatoolkit  # [ankh_variant == "cuda"]
    - pytorch >=2.2,<2.4 *cuda11*  # [ankh_variant == "cuda"]
    - pytorch >=2.2,<2.4 *cpu_*  # [ankh_variant == "cpu"]
    - tensorflow >=2.0,<2.10 *cuda11*  # [ankh_variant == "cuda"]
    - tensorflow >=2.0,<2.10 *cpu_*  # [ankh_variant == "cpu"]
    - numpy >=1.22,<=1.24.3
    - scipy
    - transformers
    - pathlib
    - scikit-learn

test:
  imports:
    - ankh

about:
  home: https://github.com/agemagician/Ankh
  summary: Optimized Protein Language Model
  license: MPL-2.0
  license_file: LICENSE.md

extra:
  identifiers:
    - doi:10.48550/arXiv.2301.06568
