# Based on https://github.com/conda-forge/php-feedstock, updated and additional modules
{% set name = "php" %}
{% set version = "8.1.16" %}
{% set sha256 = "a929fb9ed3bc364a5dea4f64954e8aaaa3408b87df04d7c6f743a190f5594e84" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://www.php.net/distributions/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0005-iconv_basic_001.phpt-iconv-update.patch
    - 0006-bug61367-read.phpt-libxml2-update.patch
    - 0007-libxml_disable_entity_loader.phpt-libxml2-update.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - bison
    - libtool
    - pkg-config
    - util-linux  # [linux]
  host:
    - libiconv
    - libxml2
    - openssl
    - re2c
    - sqlite
    - pcre2
    - zlib
    - bzip2
    - libcurl
    - libgd
    - openldap
    - libffi
    - gmp
    - libzip
    - libxslt
    - readline

test:
  commands:
    - php --version
    - php --help
    - php -m

about:
  home: https://github.com/php/php-src
  license: PHP-3.01
  license_family: OTHER
  license_file: LICENSE
  summary: PHP is a popular general-purpose scripting language that is especially suited to web development.
  description: |
    PHP is a popular general-purpose scripting language that is especially suited to web development. 
    Fast, flexible and pragmatic, PHP powers everything from your blog to the most popular websites in the world. 
    PHP is distributed under the PHP License v3.01.
  doc_url: https://www.php.net/
  dev_url: https://github.com/php/php-src

extra:
  skip-lints:
    - in_other_channels
