{% set name = "cudatoolkit" %}
{% set version = "11.2.2" %}
{% set sha256 = "0a2e477224af7f6003b49edfd2bfee07667a8148fe3627cfd2765f6ad72fa19d" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://developer.download.nvidia.com/compute/cuda/11.2.2/local_installers/cuda_11.2.2_460.32.03_linux.run
    sha256: {{ sha256 }}

build:
  number: 5
  skip: True # [osx]
  detect_binary_files_with_prefix: False
  binary_relocation: False

test:
  commands:
    - nvcc --version

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license: PROPRIETARY
  license_file: EULA.txt
  summary: 'NVIDIA CUDA Toolkit'

extra:
  skip-lints:
    - in_other_channels
    - should_be_noarch_generic
    - build_number_needs_bump

