--- code/Makefile	2019-10-23 20:20:54.000000000 -0500
+++ code/Makefile.new	2021-07-19 10:14:44.927991098 -0500
@@ -1,5 +1,3 @@
-CXX = g++
-export CXX
 CXXFLAGS = -std=c++11 -O3 -march=native -Wall -Wextra -pedantic -DNDEBUG
 
 SRCS = $(wildcard *.cpp) \
