--- kalign/Makefile.in_old	2017-06-29 21:12:22.556763389 +0000
+++ kalign/Makefile.in	2017-06-29 21:12:54.980836983 +0000
@@ -1,4 +1,3 @@
-PREFIX			= /usr/local/bin
 TEST				= test/
 CC					= gcc  
 CFLAGS			= -O9  -Wall 
@@ -29,7 +28,7 @@
 
 
 install:
-	cp $(PROGS) /usr/local/bin/
+	cp $(PROGS) ${PREFIX}/bin/
 	
 clean: 
 	rm -f $(PROGS) $(OBJECTS)
--- kalign/configure_old	2017-06-29 21:12:28.433776726 +0000
+++ kalign/configure	2017-06-29 21:13:57.990980003 +0000
@@ -253,7 +253,7 @@
 #
 # Initializations.
 #
-ac_default_prefix=/usr/local
+ac_default_prefix=${PREFIX}
 ac_config_libobj_dir=.
 cross_compiling=no
 subdirs=
