# Updated version of https://github.com/conda-forge/r-terra-feedstock
{% set name = "r-terra" %}
{% set version = "1.6-7" %}
{% set sha256 = "3470e03264836a1f9e9cc1029276b7481020042448914bc3948cd8144f3ac7dc" %}

package:
  name: {{ name }}
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/terra_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/terra/terra_{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf
    - automake
    - pkg-config
    - make
  host:
    - r-base
    - r-rcpp
    - libgdal
    - proj
    - geos
  run:
    - r-base
    - r-rcpp
    - libgdal
    - proj
    - geos

test:
  commands:
    - $R -e "library('terra')"

about:
  home: https://rspatial.org/terra
  license: GPL-3.0-or-later
  summary: Methods for spatial data analysis with raster and vector data. Raster methods allow for low-level data manipulation as well as high-level global, local, zonal, and focal computation. The predict and interpolate methods facilitate the use of regression type (interpolation, machine learning) models for spatial prediction,
    including with satellite remote sensing data. Processing of very large files is supported. See the manual and tutorials on <https://rspatial.org/terra/> to get started. 'terra' is very similar to the 'raster' package; but 'terra' can do more, is simpler to use, and it is faster.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  skip-lints:
    - in_other_channels
