{% set name = "alphafold-colabfold" %}
{% set version = "2.3.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/alphafold-colabfold/alphafold_colabfold-{{ version }}.tar.gz
  sha256: 0ad91633f1dd47c22a96fe3c29eb07e537bf6457ff21a38460e0aa9a7c5a4eeb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin="x") }}
requirements:
  host:
    - python
    - pip
    - setuptools >=42.0.0
  run:
    - python
    - absl-py
    - biopython
    - chex
    - dm-haiku
    - dm-tree
    - immutabledict
    - jax
    - ml-collections
    - numpy
    - pandas
    - scipy

test:
  imports:
    - alphafold
    - alphafold.model.model
    - alphafold.model.config
    - alphafold.model.data
    - alphafold.data.pipeline
    - alphafold.common.protein

about:
  home: https://github.com/sokrypton/alphafold
  summary: An implementation of the inference pipeline of AlphaFold v2.3.1. This is a completely new model that was entered as AlphaFold2 in CASP14 and published in Nature. This package contains patches for colabfold.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tanash
