{% set name = "netpbm" %}
{% set version = "10.73.20" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  svn_url: http://svn.code.sf.net/p/netpbm/code/stable
  svn_rev: r3269
  svn_ignore_externals: True

build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - flex
    - gettext
    - svn

  host:
    - perl
    - jpeg
    - libtiff
    - zlib
    - libpng
    - libxml2
    - xorg-libx11

  run:
    - perl
    - jpeg
    - libtiff
    - zlib
    - libpng
    - libxml2
    - xorg-libx11

test:
  commands:
    - pnmtopng -version
    - pnmtops -version
    - ppmtogif -version
    - pamscale -version
    - tifftopnm -version
    - jpegtopnm -version
    - ppmtopgm -version
    - pamcut -version
    - bmptopnm -version

about:
  home: http://netpbm.sourceforge.net
  license: GPLv2
  license_family: GPL
  license_file: doc/copyright_summary
  summary: 'Netpbm is a toolkit for manipulation of graphic images, including conversion of images between a variety of different formats.'

extra:
  skip-lints:
    - missing_hash
