{% set name = "tensorpack" %}
{% set version = "0.11" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 022b610e416e62e3575424cd08e60af27808a5fb6914294615391caf582cbd4f

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - python >=3.3
    - msgpack-python >=0.5.2
    - msgpack-numpy >=0.4.4.2
    - numpy >=1.14
    - pip
    - psutil >=5
    - python
    - pyzmq >=16
    - six
    - tabulate >=0.7.7
    - termcolor >=1.1
    - tqdm >4.29.0
  run:
    - python >=3.3
    - msgpack-python >=0.5.2
    - msgpack-numpy >=0.4.4.2
    - numpy >=1.14
    - psutil >=5
    - pyzmq >=16
    - six
    - tabulate >=0.7.7
    - termcolor >=1.1
    - tqdm >4.29.0
    - opencv

test:
  imports:
    - tensorpack
    - tensorpack.callbacks
    - tensorpack.compat
    - tensorpack.contrib
    - tensorpack.dataflow
    - tensorpack.dataflow.dataset
    - tensorpack.dataflow.imgaug
    - tensorpack.graph_builder
    - tensorpack.input_source
    - tensorpack.models
    - tensorpack.predict
    - tensorpack.tfutils
    - tensorpack.train
    - tensorpack.utils
  requires:
    - flake8
    - scikit-image
    - tensorflow * mkl*

about:
  home: "https://github.com/tensorpack/tensorpack"
  license: Apache
  license_family: APACHE
  license_file: LICENSE
  summary: "A Neural Network Training Interface on TensorFlow"
  doc_url: "https://github.com/tensorpack/tensorpack"
  dev_url: "https://github.com/tensorpack/tensorpack"
