python:
  - 3.9.*  *_cpython
  - 3.8.*  *_cpython
  - 3.7.*  *_cpython
# conda-forge only has 3 python versions, so we need to modify the length of the other zip_keys in its group
python_impl:
  - cpython
  - cpython
  - cpython
numpy:
  - 1.19.*
  - 1.17.*
  - 1.17.*
wxwidgets:
  - 3.1.*
gdal:
  - 3.*
pin_run_as_build:
  wxwidgets:
    min_pin: x.x
    max_pin: x.x
  gdal:
    min_pin: x.x
    max_pin: x.x
