# Adapted from https://github.com/bioconda/bioconda-recipes/tree/master/recipes/relion
{% set name = "RELION" %}
{% set version = "5.0.1" %}
{% set sha256 = "acbf898e96513b092514a56ff2a255c69a795e7a6f04131eacc8f55e2a900c23" %}
# Define build matrix for GPU vs. CPU
{% set relion_variant = relion_variant or "cuda" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/3dem/{{ name|lower }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches: cmake.patch

build:
  skip: True  # [py2k or py>=40 or py<39]
  number: 1000
  string: {{ relion_variant }}_py{{ py }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin="x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake <3.27
    - make
    - pkg-config
    - {{ cdt('libx11-devel') }}
    - {{ cdt('xorg-x11-proto-devel') }} 
    - cuda-nvcc  # [relion_variant == "cuda"]
    - cuda-cudart-dev  # [relion_variant == "cuda"]
    - cuda-version >=12.0,<13  # [relion_variant == "cuda"]
    - python
  host:
    - python
    - pip
    - libtiff
    - fftw
    - ghostscript
    - fltk
    - libpng
    - libcurand
    - libcurand-dev
    - libcufft
    - libcufft-dev
    - mkl
    - openmpi
    - libgomp
    - pbzip2
    - xz
    - zstd
    - tbb
    - tbb-devel
    - pytorch 2.4.1 {{ relion_variant }}*
    - torchvision >=0.15.2 {{ relion_variant }}*
    - numpy >=1.24.4
    - loguru
    - mrcfile >=1.4.3
    - starfile >=0.5.6
    - scikit-learn >=1.3.0
    - umap-learn >=0.5.3
    - matplotlib-base >=3.7.2
    - napari >=0.4.18
    - tsnecuda >=3.0.1  # [relion_variant == "cuda"]
    - tqdm >=4.65.0
    - tensorboard
    - pyqt >=5.15.9
    - typer >=0.9.0
    - biopython >=1.81
    - morphosamplers
    - pydantic
    - click <8.2.0
    - fastcluster
    - seaborn
    - dill
    - scipy
    - relion-classranker
    - relion-blush
    - dynamight
    - model-angelo
    #- topaz
  run:
    - python
    - libtiff
    - fftw
    - ghostscript
    - fltk
    - libpng
    - libcurand
    - libcurand-dev
    - libcufft
    - libcufft-dev
    - mkl
    - openmpi
    - libgomp
    - pbzip2
    - xz
    - zstd
    - tbb
    - tbb-devel
    - pytorch 2.4.1 {{ relion_variant }}*
    - torchvision >=0.15.2 {{ relion_variant }}*
    - numpy >=1.24.4
    - loguru
    - mrcfile >=1.4.3
    - starfile >=0.5.6
    - scikit-learn >=1.3.0
    - umap-learn >=0.5.3
    - matplotlib-base >=3.7.2
    - napari >=0.4.18
    - tsnecuda >=3.0.1  # [relion_variant == "cuda"]
    - tqdm >=4.65.0
    - tensorboard
    - pyqt >=5.15.9
    - typer >=0.9.0
    - biopython >=1.81
    - morphosamplers
    - pydantic
    - click <8.2.0
    - fastcluster
    - seaborn
    - dill
    - scipy
    - relion-classranker
    - relion-blush
    - dynamight
    - model-angelo
    #- topaz

test:
  commands:
    - relion_image_handler --help

about:
  home: "https://github.com/3dem/relion"
  license: "GPL-2.0-or-later"
  license_file: LICENSE
  license_family: GPL2
  summary: "Image-processing software for cryo-electron microscopy."
  dev_url: "https://github.com/3dem/relion"
  doc_url: "https://relion.readthedocs.io/en/latest"

extra:
  skip-lints:
    - in_other_channels
