{% set name = "r-phia" %}
{% set version = '0.2-1' %}
{% set sha256 = "00e402f19d857e497df771bccaf62690d5624eb73c354dbada081155e8546267" %}

package:
  name: {{ name }}
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/phia_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/phia/phia_{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  noarch: generic

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: nlme, lme4
requirements:
  host:
    - r-base
    - r-matrix
    - r-car

  run:
    - r-base
    - r-matrix
    - r-car

test:
  commands:
    - $R -e "library('phia')"

about:
  home: https://github.com/heliosdrm/phia
  license: GPLv3
  summary: "phia: Post-Hoc Interaction Analysis"
  license_family: GPL
  license_file: LICENSE.txt
