{% set name = "rtoml" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rtoml-{{ version }}.tar.gz
  sha256: 6d55fa9df88256c6762f01f18b8bd3f6dc1836600ea8655eb3719a2b8f3df764

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin="x") }}
  skip: True  # [py<37]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}
  host:
    - python
    - maturin >=1,<2
    - setuptools
    - wheel
    - setuptools-rust
    - pip
  run:
    - python

test:
  imports:
    - rtoml
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/samuelcolvin/rtoml
  summary: A better TOML library for python implemented in rust.
  license: MIT
  license_file: LICENSE

extra:
  skip-lints:
    - in_other_channels
    - version_constraints_missing_whitespace # this check raises an exception, not sure why
