{% set name = "gym" %}
{% set version = "0.10.11" %}
{% set sha256 = "69f8281e250cf3d841e725a024aa8277706a9387e8739e57f5d6f4b18eb51a2d" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install '.[all]' --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: True  # [py2k]

requirements:
  host:
    - python
    - numpy >=1.10.4
    - pip
    - pyglet >=1.2.0
    - requests >=2.0
    - scipy
    - six
    - pyglet

  run:
    - python
    - numpy >=1.10.4
    - pyglet >=1.2.0
    - requests >=2.0
    - scipy
    - six
    - pyglet
    - atari_py >=0.1.4
    - pillow
    - pyopengl
    - box2d-py >=2.3.5
    - imageio

test:
  imports:
    - gym
    - gym.envs
    - gym.envs.algorithmic
    - gym.envs.algorithmic.tests
    - gym.envs.classic_control
    - gym.envs.tests
    - gym.envs.toy_text
    - gym.envs.unittest
    - gym.spaces
    - gym.spaces.tests
    - gym.utils
    - gym.wrappers
    - gym.wrappers.monitoring
    - gym.wrappers.monitoring.tests
    - gym.wrappers.tests
  requires:
    - mock
    - pytest

about:
  home: https://gym.openai.com
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: "The OpenAI Gym: A toolkit for developing and comparing your reinforcement learning agents."
  doc_url: https://gym.openai.com/docs
  dev_url: https://github.com/openai/gym

extra:
  skip-lints:
    - should_be_noarch_generic
    - should_not_use_skip_python
    - in_other_channels
