{% set name = "Togl" %}
{% set version = "2.0" %}
{% set sha256 = "b7d4a90bbad3aca618d505ee99e7fd8fb04c829f63231dda2360f557ba3f7610" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://downloads.sourceforge.net/project/{{ name|lower}}/{{ name }}/{{ version }}/{{ name }}{{ version }}-src.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True #  [osx]
  run_exports:
    -  {{ pin_subpackage( name|lower, max_pin="x") }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ cdt('mesa-libgl-devel') }}
  host:
    - tk
    - xorg-libxmu
    - xorg-libx11
  run:
    - tk
    - xorg-libxmu
    - xorg-libx11

test:
  commands:
    - test -f ${PREFIX}/include/togl.h
    - test -f ${PREFIX}/lib/libTogl.so.2
    - test -f ${PREFIX}/lib/libTogl2.0.so
    - test -f ${PREFIX}/lib/Togl2.0/libTogl2.0.so

about:
  home: https://togl.sourceforge.net/
  dev_url: https://sourceforge.net/projects/togl/
  doc_url: https://togl.sourceforge.net/using.html
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: "A Tcl/Tk widget for OpenGL rendering."
