{% set name = "libmcfp" %}
{% set version = "1.3.3" %}
{% set sha256 = "d35e83e660c3cb443d20246fea39e78d2a11faebe3205ab838614f0280c308d0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mhekkel/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [osx]
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - zlib
    - boost-cpp
  run:
    - zlib
    - boost-cpp

test:
  commands:
    - test -e $PREFIX/include/mcfp/mcfp.hpp
    
about:
  home: https://mhekkel.github.io/libmcfp/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/mhekkel/libmcfp
  summary: "A header only library that can collect configuration options from command line arguments and configuration files."
