{% set name = "jukebox" %}
{% set version = "1.0" %}
{% set sha256 = "f6b621145df1f138f1c76c083bebc00f399948b3f3fe7bbca79dcf0486652157" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/openai/jukebox/archive/08efbbc.zip
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >3
    - pip
    - fire 0.1.3
    - tqdm 4.45.0
    - unidecode 1.1.1
    - numba 0.48.0
    - librosa 0.7.2
    - pysoundfile 0.10.3.post1
    - mpi4py >3.0.0
    - av 7.0.01
  run:
    - python >3
    - fire 0.1.3
    - tqdm 4.45.0
    - unidecode 1.1.1
    - numba 0.48.0
    - librosa 0.7.2
    - pysoundfile 0.10.3.post1
    - mpi4py >3.0.0
    - av 7.0.01
    - tensorboardX
    - pytorch-gpu
    - torchvision

test:
  imports:
    - jukebox

about:
  home: "https://openai.com/blog/jukebox/"
  dev_url: "https://github.com/openai/jukebox"
  license: Custom OSS
  license_family: OTHER
  license_file: LICENSE
  summary: "Jukebox: A Generative Model for Music."

