{% set name = "torchvision" %}
{% set version = "0.10.0" %}
{% set sha256 = "82bb2c2b03d8a65f4ea74bb0ee5566b0876a1992aceefb1e11475c7b5d2e857b" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/pytorch/vision/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - gcc_detection.patch

build:
  number: 1000
  skip: True # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - cmake
    - git
    # these should be in host: but the setup.py script looks for them in build for some unknown reason
    - ffmpeg
    - jpeg
    - libpng
  host:
    - python 3.8
    - pip
    - setuptools
    - cudatoolkit 10.1
    - hcc::pytorch-gpu 1.9.0
  run:
    - python 3.8
    - pillow >=4.1.1
    - numpy >=1.11
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}
    - hcc::pytorch-gpu 1.9.0
    - ffmpeg
    - jpeg
    - libpng

test:
  imports:
    - torchvision
    - torchvision.datasets
    - torchvision.transforms
  source_files:
    - test
  requires:
    - pytest
    - scipy
    - av
    - ca-certificates

about:
  home: https://github.com/pytorch/vision
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: 'image and video datasets and models for torch deep learning'

extra:
  skip-lints:
    - in_other_channels
