{% set name = "phono3py" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 65bf51b6b8cefb8e4a17445598242da4dfa70ccb6a7ac4da2c2d4fe70ffb927a
  patches:
    - kdeplot_latex.patch

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3
    - pip
    - numpy
    - libblas
    - libcblas
    - liblapacke
    - libgfortran
    - openblas
  run:
    - python >=3
    - pip
    - scipy
    - pyyaml
    - matplotlib-base
    - h5py
    - phonopy >=2.9.3
    - libblas * *openblas
    - openblas
    - libgfortran-ng  # [linux]
    - llvm-openmp  # [osx]
    - _openmp_mutex  # [linux]

test:
  imports:
    - phono3py

about:
  home: https://atztogo.github.io/phono3py
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A simulation package of phonon-phonon interaction related properties
  description: |
    This software calculates phonon-phonon interaction and related 
    properties using the supercell approach. 
  doc_url: https://atztogo.github.io/phono3py
  dev_url: https://github.com/atztogo/phono3py

extra:
  skip-lints:
    - in_other_channels
    - should_use_compilers
