{% set name = "starfile" %}
{% set version = "0.5.13" %}
{% set sha256 = "c9562960b06558a35c12e0bd1b8a30b71c4b676733a8b9f222c8ee94a152dc15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/starfile-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  entry_points:
    - starfile = starfile.__main__:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  run_exports:
    -  {{ pin_subpackage(name|lower, max_pin="x.x") }}

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling
    - hatch-vcs
    - setuptools-scm
  run:
    - python >=3.8
    - numpy
    - pandas >=2.1.1
    - pyarrow
    - typing-extensions

test:
  imports:
    - starfile
  commands:
    - starfile --help

about:
  home: https://github.com/alisterburt/starfile
  summary: STAR file I/O in Python
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/alisterburt/starfile
  doc_url: https://teamtomo.org/starfile/

extra:
  skip-lints:
    - in_other_channels
