{% set name = "r-paran" %}
{% set version = '1.5.2' %}
{% set sha256 = "7a089af1db4fb7ca13b588a106ce12725ce6ca6480289c5d7beeba5e07523435" %}

package:
  name: {{ name }}
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/paran_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/paran/paran_{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  noarch: generic

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-mass

  run:
    - r-base
    - r-mass

test:
  commands:
    - $R -e "library('paran')"

about:
  home: https://cran.r-project.org/package=paran
  license: GPLv2
  summary: "paran: Horn's Test of Principal Components/Factors"
  license_family: GPL
  license_file: LICENSE.txt
