{% set name = "dicomweb-client" %}
{% set version = "0.56.2" %}
{% set sha256 = "8e7782e3958dcb1db8912b5f1d689a4b9cc92e56e0684b98898c7b8c7b47beb1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  entry_points:
    - dicomweb_client = dicomweb_client.cli:_main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dicomweb-client-{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  host:
    - pip
    - python >=3
  run:
    - numpy >=1.19
    - pillow >=8.3
    - pydicom >=2.2
    - python >=3
    - requests >=2.18
    - retrying >=1.3.3
    - typing-extensions >=4.0  # [py<38]

test:
  imports:
    - dicomweb_client
  commands:
    - pip check
    - dicomweb_client --help
  requires:
    - pip

about:
  home: https://github.com/herrmannlab/dicomweb-client
  doc_url: https://dicomweb-client.readthedocs.io/en/latest/
  summary: Client for DICOMweb RESTful services.
  license: MIT
  license_file: LICENSE
