{% set name = "cbor2" %}
{% set version = "5.4.3" %}
{% set sha256 = "62b863c5ee6ced4032afe948f3c1484f375550995d3b8498145237fe28e546c2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  skip: true  # [py<37]
  script:
    - export CBOR2_BUILD_C_EXTENSION=1
    - {{ PYTHON }} -m pip install . -vv
  number: 0

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cbor2-{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools >=61
    - setuptools-scm >=6.4
  run:
    - python

test:
  imports:
    - cbor2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/cbor2/
  summary: CBOR (de)serializer with extensive tag support
  license: MIT
  license_file: LICENSE.txt
