# Based on https://github.com/conda-forge/ocaml-feedstock for old version.
{% set name = "ocaml" %}
{% set version = "3.12.0" %}
{% set version_major = version.split(".")[0] %}
{% set version_minor = version.split(".")[1] %}
{% set sha256 = "d964b385e110c1517c9de1c6331476d5e7a3585cc692b6b6b8973f3a9be7da4b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://caml.inria.fr/pub/distrib/{{ name }}-{{ version_major }}.{{ version_minor }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 001-prefix_fix.patch
    - 002-fix-assembly-failure.patch

build:
  number: 0
  skip: True  # [osx]
  run_exports:
    - {{ pin_subpackage("ocaml", max_pin="x.x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - xorg-libx11
  run:
    - {{ compiler('c') }}

test:
  commands:
    - ocaml -version
    - ocamlc -version
    - ocamlcp -version
    - ocamldoc -version
    - ocamldebug -version
    - ocamldep -version
    - ocamllex -version
    - ocamlmklib -version
    - ocamlmktop -version
#    - ocamlobjinfo -help
    - ocamlopt -version
    - ocamlprof -version
    - ocamlrun -version
    - ocamlyacc -version

about:
  home: https://ocaml.org/
  license: LGPL-2.1-only WITH OCaml-LGPL-linking-exception
  license_family: LGPL
  license_file: LICENSE
  summary: Objective Caml (OCaml) is an implementation of the ML language.
  doc_url: https://ocaml.org/docs/
  dev_url: https://github.com/ocaml/ocaml

extra:
  skip-lints:
    - in_other_channels
    - compilers_must_be_in_build
