--- makefile	2020-12-18 10:40:48.000000000 +0000
+++ makefile.new	2021-02-10 04:57:04.856508271 +0000
@@ -14,12 +14,19 @@
 	sprec = 1
 endif
 
+#default compiler
+CC ?= gcc
+CXX ?= g++
+
+# extra CUDA archicture options
+CUDA_ARCH_OPTS ?= ''
+
 #Boris program version
 BVERSION := 300
 
 #Working directories
-BORIS_DATA_DIR := Boris_Data
-BORIS_SIM_DIR := $(BORIS_DATA_DIR)/Simulations
+BORIS_DATA_DIR ?= Boris_Data
+BORIS_SIM_DIR ?= $(BORIS_DATA_DIR)/Simulations
 
 #Source directories for make
 SRC_DIR := Boris
@@ -61,18 +68,18 @@
 	@echo Done
  
 install:
-	nvcc -arch=sm_$(arch) -dlink -w $(CUOBJ_DIR)/*.o -o $(CUOBJ_DIR)/rdc_link.o 
-	g++ $(OBJ_DIR)/*.o $(CUOBJ_DIR)/*.o -fopenmp -ltbb -lsfml-graphics -lsfml-window -lsfml-system -lfftw3 -lX11 -lcudart -lcufft -lcudadevrt -o BorisLin
+	nvcc -arch=sm_$(arch) $(CUDA_ARCH_OPTS) -ccbin $(CC) -dlink -w $(CUOBJ_DIR)/*.o -o $(CUOBJ_DIR)/rdc_link.o 
+	$(CXX) $(CXXFLAGS) $(LDFLAGS) $(OBJ_DIR)/*.o $(CUOBJ_DIR)/*.o -fopenmp -ltbb -lsfml-graphics -lsfml-window -lsfml-system -lfftw3 -lX11 -lcudart -lcufft -lcudadevrt -lrt -o BorisLin
 	rm -f $(OBJ_FILES) $(CUOBJ_FILES) $(CUOBJ_DIR)/rdc_link.o
-	mkdir -p ~/Documents/$(BORIS_DATA_DIR)
-	mkdir -p ~/Documents/$(BORIS_SIM_DIR)
-	cp -f Manual/BorisManual-v$(BVERSION).pdf ~/Documents/$(BORIS_DATA_DIR)/BorisManual-v$(BVERSION).pdf
-	cp -f BorisMDB.txt ~/Documents/$(BORIS_DATA_DIR)/BorisMDB.txt
+	mkdir -p $(BORIS_DATA_DIR)
+	mkdir -p $(BORIS_SIM_DIR)
+	cp -f Manual/BorisManual-v$(BVERSION).pdf $(BORIS_DATA_DIR)/BorisManual-v$(BVERSION).pdf
+	cp -f Boris/BorisMDB.txt $(BORIS_DATA_DIR)/BorisMDB.txt
 	@echo Done
  
 Boris/Boris_o/%.o: Boris/%.cpp
-	g++ -c -Ofast -std=c++17 -IBorisLib -IBorisCUDALib -fopenmp $< -o $@
+	$(CXX) -c -Ofast -std=c++17 -IBorisLib -IBorisCUDALib -fopenmp $(CXXFLAGS)  $< -o $@
 
 Boris/Boris_cuo/%.o: Boris/%.cu
-	nvcc -rdc=true -c -std=c++14 -IBorisLib -IBorisCUDALib -w -arch=sm_$(arch) $< -o $@
+	nvcc -rdc=true -c -std=c++14 -IBorisLib -IBorisCUDALib -w -arch=sm_$(arch) $(CUDA_ARCH_OPTS) -ccbin $(CC) $< -o $@
 	
