{% set name = "hcc-jupyter-kernels" %}
{% set version = datetime.datetime.utcnow().strftime('%Y.%m.%d') %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: .

build:
  number: 0
  noarch: true
  script:
    - mkdir -p ${PREFIX}/share/hcc-jupyter-kernels
    - cp -aR kernels/* ${PREFIX}/share/hcc-jupyter-kernels

test:
  requires:
    - jupyterlab
  commands:
    - test -f ${PREFIX}/share/hcc-jupyter-kernels/common/kernels/python-3.7/kernel.json
    - test -f ${PREFIX}/share/hcc-jupyter-kernels/common/kernels/julia-1.7/wrapper_julia.sh
    - export JUPYTER_PATH=${PREFIX}/share/hcc-jupyter-kernels/common:${PREFIX}/share/hcc-jupyter-kernels/crane:${PREFIX}/share/hcc-jupyter-kernels/rhino
    - jupyter kernelspec list

about:
  home: https://git.unl.edu/hcc/hcc-conda-recipes
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: "Jupyter kernelspec files for HCC resources"

extra:
  skip-lints:
    - missing_hash
    - build_number_needs_reset
