{% set name = "cudatoolkit" %}
{% set version = "12.8.0" %}
{% set sha256 = "610867dcd6d94c4e36c4924f1d01b9db28ec08164e8af6c764f21b84200695f8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/{{ version }}/local_installers/cuda_{{ version }}_570.86.10_linux.run
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True # [osx]
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}
  detect_binary_files_with_prefix: False
  binary_relocation: False
  missing_dso_whitelist:
    - '*/ld-linux-x86-64.so.2'
    - '*/libc.so.6'
    - '*/libm.so.6'
    - '*/libpthread.so.0'
    - '*/librt.so.1'
    - '*/libutil.so.1'
    - '*/libdl.so.2'

test:
  commands:
    - nvcc --version

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license: PROPRIETARY
  license_file: EULA.txt
  summary: 'NVIDIA CUDA Toolkit'

extra:
  skip-lints:
    - in_other_channels
    - should_be_noarch_generic
    - build_number_needs_bump
