{% set version = '0.1.3' %}

package:
  name: r-mmwrweek
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/MMWRweek_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/MMWRweek/MMWRweek_{{ version }}.tar.gz
  sha256: 1aa8b687dc3340c3f277689eb0ca529e0064a4a3a66868137f2f8ab209d133d0

build:
  number: 0
  noarch: generic
  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat
requirements:
  host:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('MMWRweek')"

about:
  home: http://wwwn.cdc.gov/nndss/document/MMWR_Week_overview.pdf
  license: GPL-2
  summary: 'The first day of any MMWR week is Sunday. MMWR week numbering is sequential beginning
    with 1 and incrementing with each week to a maximum of 52 or 53. MMWR week #1 of
    an MMWR year is the first week of the year that has at least four days in the calendar
    year. This package provides functionality to convert Dates to MMWR day, week, and
    year and the reverse.'
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
    - LICENSE
