# Based on https://github.com/conda-forge/ghostscript-feedstock, modified to use conda dependencies and include headers
{% set version = "9.54.0" %}
{% set major = version.split('.')[0] %}
{% set minor = version.split('.')[1] %}

package:
  name: ghostscript
  version: {{ version }}

source:
  url: https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs{{ version | replace(".", "") }}/ghostscript-{{ version }}.tar.gz
  sha256: 0646bb97f6f4d10a763f4919c54fa28b4fbdd3dff8e7de3410431c81762cade0
  patches:
    - dynlink_runtime.patch

build:
  number: 1001

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - zlib
    - jpeg
    - libtiff
    - openjpeg
    - libpng
    - expat
    - xorg-libx11
    - xorg-libxext
    - xorg-libxt
    - freetype
    - libidn
    - jbig2dec
  run:
    - zlib
    - xorg-libx11
    - xorg-libxt

test:
  commands:
    - gs --version
    - test -f ${PREFIX}/include/ghostscript/iapi.h
    - test -f ${PREFIX}/lib/libgs${SHLIB_EXT}  # [unix]
    - test -f ${PREFIX}/lib/libgs${SHLIB_EXT}.{{ major }}  # [unix]
    - test -f ${PREFIX}/lib/libgs${SHLIB_EXT}.{{ major }}.{{ minor }}  # [unix]

about:
  home: http://ghostscript.com/
  license: AGPLv3
  license_family: AGPL
  license_file: LICENSE
  summary: An interpreter for the PostScript language and for PDF

extra:
  skip-lints:
    - in_other_channels
