{% set name = "CNVcaller" %}
{% set version = "0.0.2024.01.18" %}
{% set commit = "d851794e5eb459dd79cbfacc6376c0dfa239747b" %}
{% set sha256 = "aa8eb43cc6b177402abea042a37dd3f40136149609a8ef4d512c04da4a49c155" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/JiangYuLab/{{ name }}/archive/{{ commit }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - paths.patch

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin="x.x") }}

requirements:
  host:
    - python <3.9
    - perl
    - samtools 1.3
    - htslib 1.3
    - blasr <=5.3.2
    - numpy
    - pandas
    - click
    - scikit-learn
  run:
    - python <3.9
    - perl
    - samtools 1.3
    - htslib 1.3
    - blasr <=5.3.2
    - numpy
    - pandas
    - click
    - scikit-learn

test:
  commands:
    - 1.1.CNVprocess.pl 2>&1 | grep "1.1.CNVprocess.pl" > /dev/null 
    - 1.2.CNVcorrect.pl 2>&1 | grep "1.2.CNVcorrect.pl" > /dev/null
    - 1.3.CNVnormalize.pl 2>&1 | grep "1.3.CNVnormalize.pl" > /dev/null
    - 2.1.CNVDiscoveryMerge.pl 2>&1 | grep "2.1.CNVDiscoveryMerge.pl" > /dev/null 
    - 2.2.CNVRRedundancy.pl 2>&1 | grep "2.2.CNVRRedundancy.pl" > /dev/null 
    - CNVReferenceDB.pl 2>&1 | grep "CNVReferenceDB.pl" > /dev/null
    - Genotype.py --help
    - 0.1.Kmer_Generate.py --help
    - 0.2.Kmer_Link.py --help

about:
  home: https://github.com/JiangYuLab/CNVcaller
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: "CNVcaller is designed to detect copy number variation using sequencing data from populations."
  dev_url: https://github.com/JiangYuLab/CNVcaller

extra:
  identifiers:
    - doi:10.1093/gigascience/gix115
