{% set name = "pillow" %}
{% set version = "9.0.0.post1" %}
{% set sha256 = "918541cfaa90ba3c0e1bae5da31ba1b1f52b09c0009bd90183b787af4e018263" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://files.pythonhosted.org/packages/4e/f1/452523b163a2ca604df47aaeec4621a0a47df4c7ea6b80373777b92d3aef/Pillow-SIMD-9.0.0.post1.tar.gz"
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: True # [osx or py<37]
  script:
    - "{{ PYTHON }} -m pip install --no-deps -vv ."

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - jpeg
    - zlib
    - libtiff
    - freetype
    - openjpeg
    - libwebp
    - tk
    - libxcb
    - libimagequant
    - lcms2
  run:
    - python
    - jpeg
    - zlib
    - libtiff
    - freetype
    - openjpeg
    - libwebp
    - tk
    - libxcb
    - libimagequant
    - lcms2

test:
  imports:
    - PIL
  requires:
    - pytest

about:
  home: "https://github.com/uploadcare/pillow-simd"
  license: "Historical Permission Notice and Disclaimer (HPND)"
  license_family: OTHER
  license_file: LICENSE
  summary: "Python Imaging Library (Fork)"
  doc_url: "https://python-pillow.org/pillow-perf/"

extra:
  skip-lints:
    - in_other_channels
    - build_number_needs_reset
