{% set name = "pillow" %}
{% set version = "8.2.0" %}
{% set sha256 = "d966a27bd027d960c62ce5593858b4bf3e98ea44b9f7684a4486086b6f0ea3aa" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://github.com/uploadcare/{{ name }}/archive/{{ version }}.tar.gz"
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: True # [osx or py2k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - jpeg
    - zlib
    - libtiff
    - freetype
    - openjpeg
    - libwebp
    - tk
    - libxcb
    - libimagequant
    - lcms2
  run:
    - python
    - jpeg
    - zlib
    - libtiff
    - freetype
    - openjpeg
    - libwebp
    - tk
    - libxcb
    - libimagequant
    - lcms2

test:
  imports:
    - PIL
  requires:
    - pytest

about:
  home: "https://github.com/uploadcare/pillow-simd"
  license: "Historical Permission Notice and Disclaimer (HPND)"
  license_family: OTHER
  license_file: LICENSE
  summary: "Python Imaging Library (Fork)"

extra:
  skip-lints:
    - in_other_channels
