{% set name = "pillow" %}
{% set version = "8.3.1" %}
{% set sha256 = "bf77f392094e3bb24ca56ef8bbc4ea0d9752226ff348682d849c0aa8c1577980" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://github.com/uploadcare/{{ name }}/archive/{{ version }}.tar.gz"
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: True # [osx or py2k]
  script:
    - "{{ PYTHON }} -m pip install --no-deps -vv ."

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - jpeg
    - zlib
    - libtiff
    - freetype
    - openjpeg
    - libwebp
    - tk
    - libxcb
    - libimagequant
    - lcms2
  run:
    - python
    - jpeg
    - zlib
    - libtiff
    - freetype
    - openjpeg
    - libwebp
    - tk
    - libxcb
    - libimagequant
    - lcms2

test:
  imports:
    - PIL
  requires:
    - pytest

about:
  home: "https://github.com/uploadcare/pillow-simd"
  license: "Historical Permission Notice and Disclaimer (HPND)"
  license_family: OTHER
  license_file: LICENSE
  summary: "Python Imaging Library (Fork)"
  doc_url: "https://python-pillow.org/pillow-perf/"

extra:
  skip-lints:
    - in_other_channels
