{% set name = "guppy-gpu" %}
{% set version = "6.2.1" %}
{% set sha256 = "2bb1ae833edb1fec9ff78674f553e993c600529715b7d80f0603f5cf6b794519" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: guppy.tar.gz
  url: https://uofnelincoln.sharepoint.com/:u:/s/UNL-HollandComputingCenter/EfgLkjI1V4dIgWe9PIFEmugB4Pk0c30YXemjbhMOTWkFgA?e=MXcsq9&download=1
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [osx]
  binary_relocation: False
  script:
    - cp -R {bin,lib,data} ${PREFIX}

requirements:
  build:
  host:
  run:

test:
  commands:
    - guppy_basecaller --help
    - guppy_aligner --help
    - guppy_barcoder --help
    - minimap2 --help
  requires:
    - cuda_driver

about:
  home: "https://denbi-nanopore-training-course.readthedocs.io/en/latest/basecalling/basecalling.html"
  dev_url: "https://denbi-nanopore-training-course.readthedocs.io/en/latest/basecalling/basecalling.html"
  license: PROPRIETARY
  license_family: PROPRIETARY
  license_file: 'bin/Guppy End User License Agreement 17Feb22.pdf'
  summary: "Guppy is a data processing toolkit that contains the Oxford Nanopore Technologies’ basecalling algorithms, and several bioinformatic post-processing features."

extra:
  skip-lints:
    - should_not_use_fn
    - should_be_noarch_generic
