{% set name = "tensorflow-addons" %}
{% set version = "0.17.1" %}
{% set sha256 = "38af4e6770f9f6b791f485e1ae2cea80c9cf8eef2846be63afd859dd78c404ee" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/tensorflow/addons/archive/v{{ version }}.tar.gz
  sha256:  {{ sha256 }}
  patches:
    - pythonpath.patch
    - repo.patch

build:
  number: 0
  skip: True # [py<37 or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bazel >=3
    - rsync
    - openjdk 11
  host:
    - python
    - typeguard >=2.7
    - tensorflow-cpu >=2.7.0,<2.10.0
    - protobuf
  run:
    - python
    - typeguard >=2.7
    - protobuf
  run_constrained:
    - tensorflow >=2.7.0,<2.10.0
    - tensorflow-gpu >=2.7.0,<2.10.0

test:
  requires:
    - tensorflow >=2.7.0,<2.10.0
  imports:
    - tensorflow_addons

about:
  home: https://www.tensorflow.org/addons
  dev_url: https://github.com/tensorflow/addons
  doc_url: https://www.tensorflow.org/addons/overview
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "TensorFlow Addons is a repository of contributions that conform to well-established API patterns, but implement new functionality not available in core TensorFlow."
