{% set name = "bioread" %}
{% set version = "3.0.1" %}
{% set sha256 = "4767b09f609f085808526fd2351494cc46144bb1fd48c1a7caef4a787c985e1d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bioread-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  entry_points:
    - acq2mat=bioread.runners.acq2mat:main
    - acq2txt=bioread.runners.acq2txt:main
    - acq_info=bioread.runners.acq_info:main
    - acq_markers=bioread.runners.acq_markers:main
    - acq2hdf5=bioread.runners.acq2hdf5:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=30.3.0
    - pip
  run:
    - python >=3.6
    - numpy
    - docopt >=0.6.1
    - scipy
    - h5py

test:
  imports:
    - bioread
  commands:
    - acq2mat --help
    - acq2txt --help
    - acq_info --help
    - acq_markers --help
    - acq2hdf5 --help

about:
  home: https://github.com/uwmadison-chm/bioread
  summary: "Libraries for reading BIOPAC files."
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/uwmadison-chm/bioread

extra:
  identifiers:
    - doi:10.5281/zenodo.7595699
