--- Makefile.am.old	2026-03-07 21:46:25.619802254 +0000
+++ Makefile.am	2026-03-07 21:46:41.855790007 +0000
@@ -10,7 +10,7 @@
 OPTIMIZATION = -O3 -Wall -Wno-write-strings -funroll-loops -fomit-frame-pointer -ftree-vectorize -funsafe-math-optimizations -Wno-unused-variable -fopenmp $(OPENMP_CXXFLAGS)
 ## For mac: may need to add -Wl,-ld_classic
 ## For others: may need to remove them?
-fs_CXXFLAGS = $(OPTIMIZATION) -Wall -Wl,-ld_classic ##  -fsanitize=leak
+fs_CXXFLAGS = $(OPTIMIZATION) -Wall
 fs_LDFLAGS = $(OPTIMIZATION) -lm -static-libstdc++
 
 mixPainter_CXXFLAGS = $(OPTIMIZATION) -Wall
