{% set name = "fusioncatcher" %}
{% set version = "1.00" %}
{% set sha256 = "46cd7ab4f06160b9735b03893254171ecc387d35c12796998448cd1594775dbc" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://sourceforge.net/projects/{{ name }}/files/{{ name }}_v{{ version }}.zip
  sha256: {{ sha256 }}
  patches:
    - paths.patch

build:
  number: 0
  skip: True  # [py3k or osx]

requirements:
  build:
    - python
    - biopython >=1.50
    - bowtie
    - seqtk
    - star=2.5.2b
    - bowtie2
    - bbmap
    - blat
    - lzo
    - bwa
    - ucsc-faToTwoBit 
    - velvet
    - openpyxl
    - xlrd
    - coreutils
    - pigz
    - samtools
    - picard
    - numpy
    - setuptools
    - parallel
    - ucsc-liftover
    - oases
    - lzop
    - java-jdk
    - sra-tools=2.6.2
    - zip
  run:
    - python
    - biopython >=1.50
    - bowtie
    - seqtk
    - star=2.5.2b
    - bowtie2
    - bbmap
    - blat
    - lzo
    - bwa
    - ucsc-faToTwoBit 
    - velvet
    - openpyxl
    - xlrd
    - coreutils
    - pigz
    - samtools
    - picard
    - numpy
    - setuptools
    - parallel
    - ucsc-liftover
    - oases
    - lzop
    - java-jdk
    - sra-tools=2.6.2
    - zip

test:
  commands:
    - export FC_DB_PATH=${PREFIX}/share/${PKG_NAME}-${PKG_VERSION}/db && fusioncatcher -h
    - export FC_DB_PATH=${PREFIX}/share/${PKG_NAME}-${PKG_VERSION}/db && fusioncatcher-build -h

about:
  home: https://github.com/ndaniel/fusioncatcher
  license: GPL-3.0
  summary: "Finder of Somatic Fusion Genes in RNA-seq data."
  license_family: GPL
  license_file: LICENSE

extra:
  identifiers:
    - doi:10.1101/011650
  skip-lints:
    - uses_javajdk
