{% set name = "duo-client" %}
{% set version = "4.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/duo_client-{{ version }}.tar.gz
  sha256: 44e06bf730a201a1e1749215ef16d2c2682a73532eedd58d63663a8adabba3d3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >3
    - six
  run:
    - python >3
    - six

test:
  imports:
    - duo_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/duosecurity/duo_client_python
  summary: Reference client for Duo Security APIs
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - acaprez
