#!/bin/bash

# Remove extra space after equal signs
# to make r_spp happy.
args=`echo $@ | sed -e 's/= /=/g'`

/opt/anaconda1anaconda2anaconda3/bin/Rscript /opt/anaconda1anaconda2anaconda3/bin/run_spp.R $args
