# Based https://github.com/conda-forge/wannier90-feedstock, modified to build MPI and shared lib
{% set name = "wannier90" %}
{% set version = "3.1.0" %}
{% set sha256 = "40651a9832eb93dec20a8360dd535262c261c34e13c41b6755fa6915c936b254" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wannier-developers/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: True  # [osx]

requirements:
  build:
    - {{ compiler('fortran') }}
    - make
  host:
    - libblas
    - liblapack
    - {{ mpi }}

  run:
    - {{ mpi }}

test:
  commands:
    - wannier90.x -v
    - postw90.x -v
    - test -f ${PREFIX}/lib/libwannier${SHLIB_EXT}

about:
  home: http://www.wannier.org/
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'The Maximally-Localised Generalised Wannier Functions Code'

  description: |
    Wannier90 is an open-source code (released under GPLv2) for 
    generating maximally-localized Wannier functions and using them
    to compute advanced electronic properties of materials with high 
    efficiency and accuracy.    
  doc_url: https://github.com/wannier-developers/wannier90/tree/master/doc
  dev_url: https://github.com/wannier-developers/wannier90

extra:
  skip-lints:
    - in_other_channels
