{% set name = "tf-models-official" %}
{% set version = "2.5.0" %}
{% set sha256 = "2ccf19a0efa9146b3fc136cf82649bd1a58ce0dca1dd086b4ef01b29514d9eba" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/tensorflow/models/archive/v{{ version }}.tar.gz
  sha256:  {{ sha256 }}
  patches:
    - requirements.patch

build:
  number: 0
  noarch: python
  script:
    - cp official/pip_package/setup.py .
    - cp official/requirements.txt .
    - "{{ PYTHON }} -m pip install . --no-deps -vv -b ."

requirements:
  host:
    - python
    - pip >=3.7
    - six
    - google-api-python-client >=1.6.7
    - google-cloud-bigquery >=0.31.0
    - kaggle >=1.3.9
    - numpy >=1.15.4
    - oauth2client
    - pandas >=0.22.0
    - psutil >=5.4.3
    - py-cpuinfo >=3.3.0
    - scipy >=0.19.1
    - tensorflow-hub >=0.6.0
    - tensorflow-model-optimization >=0.4.1
    - tensorflow-datasets
    - tensorflow-addons
    - dataclasses # [py<37]
    - gin-config
    - tf_slim >=1.1.0
    - matplotlib-base
    - pyyaml >=5.1
    - opencv
    - pillow >=8
    - pycocotools
    - seqeval
    - sentencepiece
  run:
    - python >=3.7
    - six
    - google-api-python-client >=1.6.7
    - google-cloud-bigquery >=0.31.0
    - kaggle >=1.3.9
    - numpy >=1.15.4
    - oauth2client
    - pandas >=0.22.0
    - psutil >=5.4.3
    - py-cpuinfo >=3.3.0
    - scipy >=0.19.1
    - tensorflow-hub >=0.6.0
    - tensorflow-model-optimization >=0.4.1
    - tensorflow-datasets
    - tensorflow-addons
    - dataclasses # [py<37]
    - gin-config
    - tf_slim >=1.1.0
    - matplotlib-base
    - pyyaml >=5.1
    - opencv
    - pillow >=8
    - pycocotools
    - seqeval
    - sentencepiece
  run_constrained:
    - tensorflow 2.5.0
    - tensorflow-gpu 2.5.0

test:
  imports:
    - official.core
    - official.nlp
    - official.recommendation
    - official.staging
    - official.utils
    - official.vision

about:
  home: https://github.com/tensorflow/models/tree/master/official
  dev_url: https://github.com/tensorflow/models/
  doc_url: https://github.com/tensorflow/models/tree/master/official
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "The TensorFlow official models are a collection of models that use TensorFlow’s high-level APIs."
