{% set name = "metacompass" %}
{% set version = "2.0b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/marbl/MetaCompass/archive/refs/tags/v2.0-beta.tar.gz
    sha256: a74b09887c85cd7eae8e448d086ff848db1fff5153dc846c855b078779d2c7b2
    folder: MetaCompass-2.0-beta

  - url: https://github.com/marbl/MetaCompass/raw/1.12/bin/kmer-mask
    sha256: 3dc8b9cbc7653ddc29343fe64a90af8374911c7ab3c48e7754239207291aaa29
    folder: .

build:
  number: 0
  run_exports:
    - {{ pin_compatible('metacompass', max_pin="x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
  run:
    - python >=3.1
    - perl >=5.16
    - snakemake-minimal ==5.2.1
    - blast >=2.4.0
    - bowtie2 >=2.2.9
    - samtools >=1.12
    - megahit >=1.0.6
    - openjdk >=7
    - biopython
    - mash >=2.1

test:
  commands:
    - go_metacompass.py -h 2>&1 | grep 'usage' > /dev/null
about:
  home: "https://github.com/marbl/MetaCompass"
  license: "Artistic-License-2.0"
  license_file: MetaCompass-2.0-beta/LICENSE
  summary: 'MetaCompass: Reference-guided Assembly of Metagenomes.'
  dev_url: "https://github.com/marbl/MetaCompass"
  doc_url: "https://github.com/marbl/MetaCompass/wiki"

extra:
  identifiers:
    - biotools:MetaCompass
    - doi:10.1101/212506
  skip-lints:
    - in_other_channels
