{% set prefix = "octave" %}
{% set name = "io" %}
{% set version = "2.6.3" %}
{% set sha256 = "6bc63c6498d79cada01a6c4446f793536e0bb416ddec2a5201dd8d741d459e10" %}

package:
  name: {{ prefix }}-{{ name }}
  version: {{ version }}

source:
  url: https://octave.sourceforge.io/download.php?package={{ name }}-{{ version }}.tar.gz
  folder: {{ name }}-{{ version }}
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True # [osx]
  script:
    - tar -czf {{ name }}-{{ version }}.tar.gz {{ name }}-{{ version }}
    - octave -W -H --eval "pkg install -global -verbose {{ name }}-{{ version }}.tar.gz"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
  host:
    - octave
  run:
    - octave

test:
  commands:
    - octave -W -H --eval 'pkg load {{ name }}'

about:
  home: https://octave.sourceforge.io/{{ name }}/index.html
  license: GPLv3
  license_family: GPL
  license_file: {{ name }}-{{ version }}/COPYING
  doc_url: https://octave.sourceforge.io/{{ name }}/overview.html
  summary: 'Input/Output in external formats.'
