{% set name = "npinv" %}
{% set version = "1.28" %} # Also update the version string in the npinv.py file
{% set sha256 = "7fb80461ab12a2addf7af57a44f0198eff66d6e024a797e8c5517a3838725865" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/haojingshao/npInv/raw/refs/heads/master/npInv{{ version }}.jar
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin="x") }}

requirements:
  host:
    - openjdk >=8,<9
    - python
  run:
    - openjdk >=8,<9
    - python

test:
  commands:
    - npinv --help

about:
  home: https://github.com/haojingshao/npInv
  license: MIT
  summary: an accurate tool for detecting and genotyping inversion using multiple alignment long reads

extra:
  skip-lints:
    - in_other_channels
  notes: |
    npinv is Java program that comes with a custom wrapper python script which I took from peptide-shaker.
    By default "-Xms512m -Xmx1g" is set in the wrapper. If you want to overwrite it you can
    specify these values directly after your binaries. If you have _JAVA_OPTIONS
    set globally this will take precedence.
    For example run it with "npinv -Xms512m -Xmx1g"
  identifiers:
    - doi:10.1186/s12859-018-2252-9
